title:              Echoes of Curiosity
email:              bpatil2712@gmail.com
description:        Where quiet reflections meet deep dives into the corners of my curiosity.
author:             Bhavesh Patil
baseurl:            ""
url:                "https://freaky-perceptron.github.io"

# Social Profiles
twitter_username:  Bhavesh_tweeets
github_username:   freaky-perceptron
facebook_username:  
instagram_username:  bhxv.sh
linkedin_username:  bpatil2712

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
